#!/usr/bin/env bash
# Zenflow mock Planning Core — Slice 3 only.
# Replaced by the real Planning Core in Slice 7.
#
# Generates a mock sliced implementation plan for a story and writes it to a
# temp directory, then prints the temp directory path to stdout.
#
# Usage:
#   bash mock-planning-core.sh <story_id> [target_branch]
#
# Output:
#   /tmp/zenflow-plan-<story_id>/
#     plan.md
#     status.md
#     slices/
#       01-<slug>.slice.md
#       02-<slug>.slice.md
#       ...

set -euo pipefail

STORY_ID="${1:?Usage: mock-planning-core.sh <story_id> [target_branch]}"
TARGET_BRANCH="${2:-main}"

OUT_DIR="/tmp/zenflow-plan-${STORY_ID}"
SLICES_DIR="${OUT_DIR}/slices"

mkdir -p "${SLICES_DIR}"

# ---------------------------------------------------------------------------
# plan.md
# ---------------------------------------------------------------------------
cat > "${OUT_DIR}/plan.md" <<PLAN
# ${STORY_ID} — Implementation Plan

> **Note:** Generated by mock Planning Core (Slice 3). Real plan generation in Slice 7.

## Story

**${STORY_ID}** — Mock story title for ${STORY_ID}

## Target Branch

\`${TARGET_BRANCH}\`

## Implementation Slices

| # | Slice | Notes |
|---|-------|-------|
| 1 | Set up project structure | Scaffold directories and base files |
| 2 | Implement core logic | Main feature implementation |
| 3 | Add tests | Unit and integration tests |

## Assumptions

- Standard project layout follows existing conventions in the repo
- No external service changes required beyond the story scope
- Tests use the existing test framework already in the project
PLAN

# ---------------------------------------------------------------------------
# status.md
# ---------------------------------------------------------------------------
cat > "${OUT_DIR}/status.md" <<STATUS
# ${STORY_ID} — Slice Status

**Current slice:** 1 of 3
**Story:** Mock story title for ${STORY_ID}

| # | Slice | Status |
|---|-------|--------|
| 1 | Set up project structure | ⬜ Not started |
| 2 | Implement core logic | ⬜ Not started |
| 3 | Add tests | ⬜ Not started |
STATUS

# ---------------------------------------------------------------------------
# slices/
# ---------------------------------------------------------------------------
cat > "${SLICES_DIR}/01-project-structure.slice.md" <<SLICE1
# Slice 1 — Set up project structure

**Status:** Not started

## Goal

Scaffold the directories and base files needed for this feature. Establish
the entry point and any configuration the subsequent slices will depend on.

## Tasks

- [ ] Create feature directory structure
- [ ] Add base entry point file with placeholder exports
- [ ] Verify existing tests still pass after scaffold

## Done when

All placeholder files are in place and no existing tests are broken.
SLICE1

cat > "${SLICES_DIR}/02-core-logic.slice.md" <<SLICE2
# Slice 2 — Implement core logic

**Status:** Not started

## Goal

Implement the main feature logic described in the story. This is the
primary deliverable for the story.

## Tasks

- [ ] Implement the feature as described in the story acceptance criteria
- [ ] Wire up any required dependencies or imports
- [ ] Manually verify the feature works end-to-end

## Done when

The feature behaves as described in the story. Manual verification passes.
SLICE2

cat > "${SLICES_DIR}/03-tests.slice.md" <<SLICE3
# Slice 3 — Add tests

**Status:** Not started

## Goal

Cover the core logic with tests. Use the project's existing test framework.

## Tasks

- [ ] Write unit tests for core logic
- [ ] Write at least one integration test for the happy path
- [ ] All tests pass

## Done when

Test suite passes with no failures. Coverage includes the happy path and at
least one error case.
SLICE3

# Print the output directory path for the caller
echo "${OUT_DIR}"
